export const countries = [
    {
        id: "usa",
        name: "EE.UU. y Canadá",
        min: 18,
        max: 25,
        default: 20,
        culture: "La propina es fundamental para el salario de los camareros. Se espera entre un 18% y 25%. No dejarla se considera una falta grave en la cultura norteamericana.",
    },
    {
        id: "esp",
        name: "España",
        min: 0,
        max: 10,
        default: 5,
        culture: "Opcional. Se suele redondear el cambio o dejar un 5-10% en cenas si el servicio ha sido de calidad.",
    },
    {
        id: "jpn",
        name: "Japón",
        min: 0,
        max: 0,
        default: 0,
        culture: "No se deja propina. Se considera un insulto a la profesionalidad. Si dejas dinero, es probable que te sigan para devolvértelo.",
    },
    {
        id: "ita",
        name: "Italia",
        min: 0,
        max: 10,
        default: 0,
        culture: "El 'coperto' es un cargo por el servicio de mesa, pan y mantel, no es la propina en sí. Dejar un extra del 5-10% es un gesto apreciado pero totalmente opcional.",
    },
    {
        id: "fra",
        name: "Francia",
        min: 0,
        max: 10,
        default: 5,
        culture: "El servicio está incluido por ley. Se deja el 'pourboire' (pequeño extra) solo por un trato excepcional.",
    },
    {
        id: "gbr",
        name: "Reino Unido",
        min: 0,
        max: 12.5,
        default: 10,
        culture: "A menudo se añade un 12.5% opcional en la factura. Si no está, un 10% es lo estándar en restaurantes.",
    },
    {
        id: "mex",
        name: "México",
        min: 10,
        max: 15,
        default: 12,
        culture: "Se espera 'la propina' del 10 al 15%. Es una parte vital de la economía de los trabajadores del sector.",
    },
    {
        id: "arg",
        name: "Argentina",
        min: 0,
        max: 10,
        default: 10,
        culture: "El estándar es un 10%. Casi siempre se deja si el servicio ha sido normal o bueno.",
    },
    {
        id: "bra",
        name: "Brasil",
        min: 0,
        max: 10,
        default: 10,
        culture: "Normalmente se incluye un cargo del 10% en la cuenta como 'Serviço'. Es opcional pero la mayoría lo paga.",
    },
    {
        id: "deu",
        name: "Alemania",
        min: 5,
        max: 10,
        default: 7,
        culture: "Se suele redondear o añadir un 5-10%. Se le dice al camarero el total incluyendo propina al pagar.",
    },
    {
        id: "tur",
        name: "Turquía",
        min: 5,
        max: 10,
        default: 10,
        culture: "En sitios turísticos se espera un 10% en efectivo. No se suele poder añadir a la tarjeta.",
    },
    {
        id: "aus",
        name: "Australia",
        min: 0,
        max: 10,
        default: 0,
        culture: "No es esperada. Los salarios son altos. En cenas de lujo se puede dejar un 10%.",
    },
    {
        id: "chn",
        name: "China",
        min: 0,
        max: 0,
        default: 0,
        culture: "Históricamente no se deja propina y en muchos sitios está prohibido o se considera raro.",
    },
    {
        id: "prt",
        name: "Portugal",
        min: 0,
        max: 10,
        default: 5,
        culture: "Se acostumbra dejar el cambio o redondear. En zonas turísticas un 5-10% es común.",
    },
    {
        id: "grc",
        name: "Grecia",
        min: 0,
        max: 10,
        default: 5,
        culture: "Suele bastar con redondear la cuenta. Un 5-10% extra es muy apreciado pero no obligatorio.",
    },
];
